name: Build YouUp

on:
  push:
    branches:
    - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build
      run: yarn build
    - name: Pack application
      shell: powershell
      run: |
        Invoke-WebRequest https://github.com/dgiagio/warp/releases/download/v0.3.0/windows-x64.warp-packer.exe -OutFile windows-x64.warp-packer.exe;
        .\windows-x64.warp-packer.exe -a windows-x64 -i deploy\win32\build\CHANGEME --exec qode.exe --output CHANGEME_${{ github.sha }}.exe
    - uses: actions/upload-artifact@v2
      with:
        name: CHANGEME_CI_BUILD.exe
        path: CHANGEME_${{ github.sha }}.exe